[main]
shell=bash
title=foot
font=Ligconsolata Mono Font:size=13
font-bold=Ligconsolata Mono Font:size=13
# font=JetBrains Mono Nerd Font:size=13
# font-bold=false
letter-spacing=-1
dpi-aware=no
pad=9x9
bold-text-in-bright=no
gamma-correct-blending=no
opacity=20
initial-color-theme=dark
initial-window-size-pixels=1081x527

[csd]
border-width=2

[scrollback]
lines=10000

[cursor]
style=beam
beam-thickness=1.5

[colors-dark]
# alpha=0.58
alpha=0.84
blur=yes
# include=~/.config/foot/colors-dark.ini

#background=#96a19a
#(基本可用) background=949d9a
background=696d6b
# background=#505452
# background=474b49
# foreground=#dcf0ec
foreground=81f5eb
selection-foreground=f7e7fc
selection-background=969689
# cursor = 141218 d0bcff
regular0=565858
regular1=D3DCC0
# regular2=CD6161
regular2=ea6567
regular3=B8D8A5
regular4=D6A9C8
regular5=1C051C
regular6=99DBA5
regular7=DAD3B0
bright0=B8DC79
# bright1=CC595B
bright1=CD6161
bright2=D7B2C9
bright3=BFD5B4
bright4=76A7D2
bright5=C189D1
bright6=BBDC99
bright7=6AD1D9
dim-blend-towards=white

[key-bindings]
scrollback-up-page=Page_Up
scrollback-down-page=Page_Down
search-start=Control+Shift+f

[search-bindings]
cancel=Escape
find-prev=Shift+F3
find-next=F3
